In [6]:
import matplotlib.pyplot as plt
import numpy as np
import os
import PIL
import tensorflow as tf
import pathlib
import glob

from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential

CLASSNAMES = ['mask_weared_incorrect', 'with_mask', 'without_mask']

batch_size = 32
img_height = 180
img_width = 180

model = tf.keras.models.load_model('saved_model/my_model')

# Check its architecture
model.summary()



Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 sequential (Sequential)     (None, 180, 180, 3)       0         
                                                                 
 rescaling_1 (Rescaling)     (None, 180, 180, 3)       0         
                                                                 
 conv2d (Conv2D)             (None, 180, 180, 16)      448       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 90, 90, 16)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 90, 90, 32)        4640      
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 45, 45, 32)       0         
 2D)                                                  

In [7]:
testing_images = glob.glob('./testing/*.*')

for test_image in testing_images:
    image_path = pathlib.Path(test_image)

    img = tf.keras.utils.load_img(
        image_path, target_size=(img_height, img_width)
    )
    img_array = tf.keras.utils.img_to_array(img)
    img_array = tf.expand_dims(img_array, 0) # Create a batch

    predictions = model.predict(img_array)
    score = tf.nn.softmax(predictions[0])
    print(test_image)
    print(score)
    print(CLASSNAMES[np.argmax(score)])
    print('---------------------------------------')

./testing/4.png
tf.Tensor([0.38116774 0.5825285  0.03630376], shape=(3,), dtype=float32)
with_mask
---------------------------------------
./testing/5.jpg
tf.Tensor([2.0735718e-02 9.7926188e-01 2.4711526e-06], shape=(3,), dtype=float32)
with_mask
---------------------------------------
./testing/6.png
tf.Tensor([0.12809786 0.05506166 0.8168404 ], shape=(3,), dtype=float32)
without_mask
---------------------------------------
./testing/2.png
tf.Tensor([0.20740433 0.68122786 0.11136782], shape=(3,), dtype=float32)
with_mask
---------------------------------------
./testing/3.jpg
tf.Tensor([0.2263903  0.14713429 0.6264754 ], shape=(3,), dtype=float32)
without_mask
---------------------------------------
./testing/1.png
tf.Tensor([1.4860712e-03 9.9851352e-01 3.8298856e-07], shape=(3,), dtype=float32)
with_mask
---------------------------------------
